import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/Sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Movies app",
  description: "Generated by create next app",
  icons: "/portret.png",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="flex bg-dark-blue">
        <Sidebar />
        <main className="flex-1 ml-24 my-5 mr-4">{children}</main>
      </body>
    </html>
  );
}
