export const DEFAULT_MOVIES = [
  {
    id: 1,
    title: "The Shawshank Redemption",
    year: 1994,
    rating: 9.2,
    genres: ["Drama"],
    backdrop: "/65D7t8wgZFpjOTvIp1HQvHFY0fC.jpg",
  },
  {
    id: 2,
    title: "The Godfather",
    year: 1972,
    rating: 9.2,
    genres: ["Crime", "Drama"],
    backdrop: "/tcheoA2nPATCm2vvXw2hVQoaEFD.jpg",
  },
  {
    id: 3,
    title: "The Dark Knight",
    year: 2008,
    rating: 9.0,
    genres: ["Action", "Crime", "Drama", "Thriller"],
    backdrop: "/deHMJAi10p2drYjnYi4IbSXpAqV.jpg",
  },
];
export const genres = {
  28: "Action",
  12: "Adventure",
  16: "Animation",
  35: "Comedy",
  80: "Crime",
  18: "Drama",
  10751: "Family",
  14: "Fantasy",
  36: "History",
  27: "Horror",
  10402: "Music",
  9648: "Mystery",
  10749: "Romance",
  878: "Science Fiction",
  53: "Thriller",
  10752: "War",
  37: "Western",
};
